framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope:
            sender: 'dmp@martinruzek.cz'
        headers:
            from: 'Projekty a kroužky SPŠ Ostrov <dmp@martinruzek.cz>'
            X-Auto-Response-Suppress: 'OOF, DR, RN, NRN, AutoReply'
